### ISSUE TITLE
IllegalArgumentException thrown while attempting to log in

### ISSUE THREAD

**Issue by lukabartolicFS** [GreenButtonAlliance/OpenESPI-DataCustodian-java#275]
After successful setup of OpenESPI DataCustodian application and successful OpenESPI-GreenButtonCMDTest project setup, following exception is being thrown on DataCustodian login screen:

`Named query not found: RetailCustomer.findByUsername; nested exception is java.lang.IllegalArgumentExeption: Named query not found: RetailCustomer.findByUsername`

Everything was set up following OpenESPI-DataCustidian-java and OpenESPI-GreenButtonCMDTest setup instructions. Also, Virtual Machine was also utilized _in order to automate the process of testing DataCustodian (and ThirdParty) implementation features_.

**Expected behaviour:**
- successful login using either DC user credentails (i.e. grace:koala) or RC user credentials (i.e. alan:koala)

1) What to do in order to access the system using database user data successfully and experiment with local development sandbox environment?
2) in order to implement GreenButton API, **is there any additional requirement other than** setting up DataCustodian implementation (local sandbox) with database set up and filled up with data and having OpenESPI-GreenButtonCMDTest configured?

Thanks.

**Comment by dfcoffin** [comment]
@lukabartolicFS Did you initialize the underlying database using 

`.initilizedatabases.sh` 

It is located in the /etc directory of the OpenESPI-Common-java repository.  The `develop` branch contains an updated version which resolves a Foreign Key issue if the `retail_customer` table isn't loaded first.

**Comment by lukabartolicFS** [comment]
@dfcoffin that's right, I initialized the underlying database and completely set it up. I used `toRegression.sh` script which actually calls `initializedatabase.sh`. Also, I managed to all of the configuration using SOAPUI project, but for some reason `Named query not found` exception is being thrown whatever I do.

Also, Virtual machine that I set up uses the image that is provided by GreenButton. 

Regarding `develop` branch, I tried setting up that version as well - however, I found out that one uses `Java 8` version instead of `Java 7` so I had to upgrade underlying software, as well as switch 
 DataCustodian (OpenESPI-DataCustidian-java) to `develop` branch to use upgraded version of the environment. Switching to `develop` and using higher version along with your configuration ended up in throwing `HTTP Status 500` error on application boot-up:
```
org.apache.jasper.JasperException: Unable to compile class for JSP: 
An error occurred at line: 1 in the generated java file
The type java.io.ObjectInputStream cannot be resolved. It is indirectly referenced from required .class files  
```

I would like to proceed with `master` branch as it seems to be working better with project's configuration. However, I am out of ideas as whatever I do (either locally or in GreenButton's virtual machine) I end up getting
`Named query not found: RetailCustomer.findByUsername; nested exception is java.lang.IllegalArgumentExeption: Named query not found: RetailCustomer.findByUsername`

Any other ideas?
Thanks for your assistance!

**Comment by dfcoffin** [comment]
I have both the Master and develop branches running in IntelliJ IDEA as separate projects able to logon and communicate with each other using Java 1.8.  I am running in the latest Ubuntu LTS release using VMWare's latest Windows application.

Can you provide more additional information about your environment?

**Comment by lukabartolicFS** [comment]
Quick recap based on recent events:

**Finally managed to get it up and running** by manually changing configuration values to fix dependency related issues:

1. At first, everything was set up following` OpenESPI-DataCustidian-java`, `OpenESPI-Common-java`, `OpenESPI-GreenButtonCMDTest` setup instructions on both host machine and virtual machine (utilizing GreenButtons VM image) using code base on master branch. Error that keept popping out:

`Named query not found: RetailCustomer.findByUsername; nested exception is java.lang.IllegalArgumentExeption: Named query not found: RetailCustomer.findByUsername`

2. Upgrading to Java/JDK 8 and migrating from master branch to develop branch resulted in different exceptions such as **HTTP 500** on application boot-up:

```
org.apache.jasper.JasperException: Unable to compile class for JSP: 
An error occurred at line: 1 in the generated java file
The type java.io.ObjectInputStream cannot be resolved. It is indirectly referenced from required .class files  
```

3. After some time spent researching and verifying dependencies used by the project (Maven), I found out that Tomcat version used on master branch was **6.0.29** (pretty outdated and deprecated) and on develop branch **7.0.30**. Software solution on develop branch used newer version of Java/JDK and Tomcat, but after researching I found out that Java/Javac (version 8) and Tomcat (version 7.0.30) versions do not align and don't play well together. The solution that resolved those isues was at the end really simple, but very hard to find and locate.

**Solution:**  
_DEVELOP branch, Java 8 locally installed and path of Java and Javac correctly set_

```
<plugin>
	<groupId>org.apache.tomcat.maven</groupId>
	<artifactId>tomcat7-maven-plugin</artifactId>
	<version>2.2</version> <-------------- updated from 2.0 to 2.2
	<configuration>
	    <path>/DataCustodian</path>
	    <url>http://sandbox.greenbuttonalliance.org:8443/manager/text</url>
	    <server>TomcatServerDeployment</server>
	</configuration>
</plugin>
```

Version of tomcat7-maven-plugin must be set to **2.2** instead of 2.0, because 2.0 uses outdated version of Apache Tomcat server (7.0.30) and 2,2 uses **7.0.47** which works well with remaining configuration and environment setup (dependencies).

**Current setup in use which works (so far, currently testing it out):**

- OpenESPI-DataCustidian-java DEVELOP branch (Java 8, Tomcat 7.0.47, tomcat7-maven-plugin 2.2)
- OpenESPI-Common-java DEVELOP branch (Java 8, default)
- OpenESPI-GreenButtonCMDTest MASTER branch (default)

There was something wrong with the project/Maven configuration so I assume some modifications must be made in the repository so other people don't face aforementioned issues.
This solution works for me and if I find any other issue or error I will make sure to document it.

Please provide your feedback and let me know if this finding related to the solution to reported issue makes sense.

Thanks.

**Comment by dfcoffin** [comment]
@lukabartolicFS Thanks for doing the leg work to resolve this issue.  I'm currently using Java 8, Tomcat 9.0.13 (IntelliJ IDEA default), and will upgrade my develop branch to tomcat7-maven-plugin 2.2.  I have several uncommitted clean-up revisions I'm working on in my local repository, and will merge them to the develop branch as soon as possible.  Let me know if you find any other issues.

Currently, attempting to upgrade to Java 11+ has a significant dependency issue with the current XML date processing.

My current goal is to upgrade to using Spring Boot, which should correct the type of issue you discovered, but is a non-trivial effort, given the technology shift done by Pivotal since this system was developed.  The other significant change is how Pivotal is modifying their OAuth 2.0 support.
