### ISSUE TITLE
Difficulty executing the tests or server

### ISSUE THREAD

**Issue by matteosimone** [GreenButtonAlliance/OpenESPI-DataCustodian-java#297]
Hi,

I am trying to run the tests/server and have not been able to follow the README instructions. When running the tests, I run into the error: `java.lang.NoClassDefFoundError: java/sql/SQLException` and when running the server, there are several similar errors like: `SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:/Users/matteo/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar!/] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19 `.

I have tried running on Java 11 and Java 15. Below is a sample Dockerfile that reproduces the issue
```
FROM openjdk:11.0.12

RUN set -ex \
    && apt-get update \
    && apt-get install maven -y \
    && cd /root \
    && git clone https://github.com/GreenButtonAlliance/OpenESPI-Common-java.git \
    && git clone https://github.com/GreenButtonAlliance/OpenESPI-DataCustodian-java.git \
    && cd /root/OpenESPI-Common-java \
    && mvn -Dmaven.test.skip=true -B clean install

WORKDIR /root/OpenESPI-DataCustodian-java
RUN mvn -B clean install
RUN mvn test

ENTRYPOINT ["mvn", "tomcat7:run"]
```

Could you help me figure out where I am going wrong?

**Comment by dfcoffin** [comment]
@matteosimone The JUnit/Cucumber test was created by the initial developers (Pivotal) of the platform but was never maintained and updated by subsequent supporters.  They used the SoapUI open-source platform to perform all regression testing of the platform.  If you review the test source code you will find many contain the @ignore annotation.

The current platform uses Java 7 as the expected JDK version, which may be a source of some of your issues.

Did you build the OpenESPI-Common-java jar file, which is a dependency of the OpenESPI-DataCustodian-java repository?

**Comment by matteosimone** [comment]
I ran into the similar problem trying to run the tomcat server. I did build commons, but I had to use Java 11 because that is the version expected by OpenESPI-Common-java. Is there a compatibility expectation with the version of Common expected by this repo? I will try running a different version to see if these errors are reproduced.
